- name: create user and add ssh
  hosts: all
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no

    - name: remote_username
      prompt: Act as which remote user?
      private: no

  remote_user: "{{remote_username}}"
  become: yes
  tasks:

    - name: Add the user
      ansible.builtin.user:
        name: "{{ username }}" 
        home: "/home/{{ username }}"
        password: "$6$SLz6WGrGrJCZQrd.$6TzGefulz5Qcz7QVPZtT5Aw10KUfVcV/yS2a4ZznKoL0arDtIaDnDdps3r7NEx3gdZzwV2joslW.YvyMeSnYc1"
        append: yes
        groups: wheel, root

    # - name: Expire password
      # ansible.builtin.shell: passwd marce --expire
