- name: Get storage info from a target server
  hosts: missing
  remote_user: thomase
  become: yes
  tasks:

    - name: Test some outputs.
      ansible.builtin.shell: "df -h > test.mve && a=`wc -l test.mve | awk '{print $1}'` && a=$(( $a - 1)) && rm test.mve"

    - name: Get hostname.
      ansible.builtin.shell: "uname -n"
      register: hostname

    - name: Get storage
      ansible.builtin.shell: "df -h | awk '{print $2,$4,$6}' | tail -$a"
      register: storage

    - name: Get cpus
      ansible.builtin.shell: "lscpu | grep 'CPU(s):' | head -1 |awk '{print $1,$2}'"
      register: cpus

    - name: Get memory usage
      ansible.builtin.shell: "free -h | grep Mem | awk '{print $2,$4}'"
      register: memory

    - name: Dump locally
      local_action:
        module: ansible.builtin.template
        src: ./template.j2
        dest: "./results/{{ hostname.stdout }}.j2"
        owner: "thomasvanerven"
