- name: Ansible Create user functionlity module demo
  hosts: test_vocabs:demo_vocabs:prod_vocabs:teasy:peasy:easy:demo_archaeology:test_archaeology:prod_archaeology 
  remote_user: thomase 
  become: yes
  tasks:

# Creating the user marce
    - name: Add the user 'marce'
      ansible.builtin.user:
        name: marce 
        home: /home/marce
        password: "$6$jjFQ1vphoLt3z79m$eoZtUIYc2AG07oLdlsbDgtrfFiyPC.KWsI7EYpjMReppFA00IU5SdHIretld0Ab1zFeoLkNFQEd554W.J7jWX1"

    - name: Copy ssh key for user 'marce'
      authorized_key:
        user: marce
        state: present
        key: "{{ lookup('file','/Users/thomasvanerven/Projects/devops-ansible/keys/id_rsa.pub') }}"

    - name: Add the user 'marce' with a bash shell, appending the group 'wheel' to the user's groups
      ansible.builtin.user:
        name: marce
        shell: /bin/bash
        groups: wheel
        append: yes
